local require = GLOBAL.require
local containers = require "containers"
local FOODTYPE = GLOBAL.FOODTYPE

local SALTBOX_ENABLE = GetModConfigData("SALTBOX_ENABLE")

Assets = 
{
    Asset("ANIM", "anim/ui_chest_5x5.zip"),
    Asset("ANIM", "anim/ui_portal_shadow_5x5.zip"),
}

local params = {}

local containers_widgetsetup_base = containers.widgetsetup
function containers.widgetsetup(container, prefab, data, ...)
    local t = params[prefab or container.inst.prefab]
    if t ~= nil then
        for k, v in pairs(t) do
            container[k] = v
        end
        container:SetNumSlots(container.widget.slotpos ~= nil and #container.widget.slotpos or 0)
    else
        containers_widgetsetup_base(container, prefab, data, ...)
    end
end

local function makeChest()
    local container =
    {
        widget =
        {
            slotpos = {},
            animbank = "ui_chest_5x5",
            animbuild = "ui_chest_5x5",
            pos = GLOBAL.Vector3(0, 200, 0),
            side_align_tip = 160,
        },
        type = "chest",
    }

    for y = 3, -1, -1 do
        for x = -1, 3 do
            table.insert(container.widget.slotpos, GLOBAL.Vector3(80 * x - 80 * 2 + 80, 80 * y - 80 * 2 + 80, 0))
        end
    end

    return container
end

if SALTBOX_ENABLE == true then
      params.saltbox = makeChest()
      function params.saltbox.itemtestfn(container, item, slot)
    return ((item:HasTag("fresh") or item:HasTag("stale") or item:HasTag("spoiled"))
        and item:HasTag("cookable")
        and not item:HasTag("deployable")
        and not item:HasTag("smallcreature")
        and item.replica.health == nil)
        or item:HasTag("saltbox_valid")
      end
end

for k, v in pairs(params) do
    containers.MAXITEMSLOTS = math.max(containers.MAXITEMSLOTS, v.widget.slotpos ~= nil and #v.widget.slotpos or 0)
end

--------------Tuning--------------

TUNING.PERISH_SALTBOX_MULT = GetModConfigData("saltbox_config");

--------------Items--------------

local PREFABS_FOR_POSTINIT = {
"dustmeringue",
"asparagussoup",
"asparagussoup_spice_chili",
"asparagussoup_spice_garlic",
"asparagussoup_spice_salt",
"asparagussoup_spice_sugar",
"baconeggs",
"baconeggs_spice_chili",
"baconeggs_spice_garlic",
"baconeggs_spice_salt",
"baconeggs_spice_sugar",
"bananapop",
"bananapop_spice_chili",
"bananapop_spice_garlic",
"bananapop_spice_salt",
"bananapop_spice_sugar",
"bananajuice",
"bananajuice_spice_chili",
"bananajuice_spice_garlic",
"bananajuice_spice_salt",
"bananajuice_spice_sugar",
"barnaclinguine",
"barnaclinguine_spice_chili",
"barnaclinguine_spice_garlic",
"barnaclinguine_spice_salt",
"barnaclinguine_spice_sugar",
"barnaclesushi",
"barnaclesushi_spice_chili",
"barnaclesushi_spice_garlic",
"barnaclesushi_spice_salt",
"barnaclesushi_spice_sugar",
"barnaclepita",
"barnaclepita_spice_chili",
"barnaclepita_spice_garlic",
"barnaclepita_spice_salt",
"barnaclepita_spice_sugar",
"meatysalad",
"meatysalad_spice_chili",
"meatysalad_spice_garlic",
"meatysalad_spice_salt",
"meatysalad_spice_sugar",
"bisque",
"bisque_spice_chili",
"bisque_spice_garlic",
"bisque_spice_salt",
"bisque_spice_sugar",
"veggieomlet",
"veggieomlet_spice_chili",
"veggieomlet_spice_garlic",
"veggieomlet_spice_salt",
"veggieomlet_spice_sugar",
"bunnystew",
"bunnystew_spice_chili",
"bunnystew_spice_garlic",
"bunnystew_spice_salt",
"bunnystew_spice_sugar",
"butterflymuffin",
"butterflymuffin_spice_chili",
"butterflymuffin_spice_garlic",
"butterflymuffin_spice_salt",
"butterflymuffin_spice_sugar",
"californiaroll",
"californiaroll_spice_chili",
"californiaroll_spice_garlic",
"californiaroll_spice_salt",
"californiaroll_spice_sugar",
"caviar",
"caviar_spice_chili",
"caviar_spice_garlic",
"caviar_spice_salt",
"caviar_spice_sugar",
"ceviche",
"ceviche_spice_chili",
"ceviche_spice_garlic",
"ceviche_spice_salt",
"ceviche_spice_sugar",
"coffee",
"coffee_spice_chili",
"coffee_spice_garlic",
"coffee_spice_salt",
"coffee_spice_sugar",
"mashedpotatoes",
"mashedpotatoes_spice_chili",
"mashedpotatoes_spice_garlic",
"mashedpotatoes_spice_salt",
"mashedpotatoes_spice_sugar",
"dragonpie",
"dragonpie_spice_chili",
"dragonpie_spice_garlic",
"dragonpie_spice_salt",
"dragonpie_spice_sugar",
"potatotornado",
"potatotornado_spice_chili",
"potatotornado_spice_garlic",
"potatotornado_spice_salt",
"potatotornado_spice_sugar",
"feijoada",
"feijoada_spice_chili",
"feijoada_spice_garlic",
"feijoada_spice_salt",
"feijoada_spice_sugar",
"figatoni",
"figatoni_spice_chili",
"figatoni_spice_garlic",
"figatoni_spice_salt",
"figatoni_spice_sugar",
"frognewton",
"frognewton_spice_chili",
"frognewton_spice_garlic",
"frognewton_spice_salt",
"frognewton_spice_sugar",
"figkabab",
"figkabab_spice_chili",
"figkabab_spice_garlic",
"figkabab_spice_salt",
"figkabab_spice_sugar",
"koalefig_trunk",
"koalefig_trunk_spice_chili",
"koalefig_trunk_spice_garlic",
"koalefig_trunk_spice_salt",
"koalefig_trunk_spice_sugar",
"fishtacos",
"fishtacos_spice_chili",
"fishtacos_spice_garlic",
"fishtacos_spice_salt",
"fishtacos_spice_sugar",
"fishsticks",
"fishsticks_spice_chili",
"fishsticks_spice_garlic",
"fishsticks_spice_salt",
"fishsticks_spice_sugar",
"jammypreserves",
"jammypreserves_spice_chili",
"jammypreserves_spice_garlic",
"jammypreserves_spice_salt",
"jammypreserves_spice_sugar",
"flowersalad",
"flowersalad_spice_chili",
"flowersalad_spice_garlic",
"flowersalad_spice_salt",
"flowersalad_spice_sugar",
"frogglebunwich",
"frogglebunwich_spice_chili",
"frogglebunwich_spice_garlic",
"frogglebunwich_spice_salt",
"frogglebunwich_spice_sugar",
"frozenbananadaiquiri",
"frozenbananadaiquiri_spice_chili",
"frozenbananadaiquiri_spice_garlic",
"frozenbananadaiquiri_spice_salt",
"frozenbananadaiquiri_spice_sugar",
"fruitmedley",
"fruitmedley_spice_chili",
"fruitmedley_spice_garlic",
"fruitmedley_spice_salt",
"fruitmedley_spice_sugar",
"guacamole",
"guacamole_spice_chili",
"guacamole_spice_garlic",
"guacamole_spice_salt",
"guacamole_spice_sugar",
"gummy_cake",
"gummy_cake_spice_chili",
"gummy_cake_spice_garlic",
"gummy_cake_spice_salt",
"gummy_cake_spice_sugar",
"hardshell_tacos",
"hardshell_tacos_spice_chili",
"hardshell_tacos_spice_garlic",
"hardshell_tacos_spice_salt",
"hardshell_tacos_spice_sugar",
"honeyham",
"honeyham_spice_chili",
"honeyham_spice_garlic",
"honeyham_spice_salt",
"honeyham_spice_sugar",
"honeynuggets",
"honeynuggets_spice_chili",
"honeynuggets_spice_garlic",
"honeynuggets_spice_salt",
"honeynuggets_spice_sugar",
"icecream",
"icecream_spice_chili",
"icecream_spice_garlic",
"icecream_spice_salt",
"icecream_spice_sugar",
"icedtea",
"icedtea_spice_chili",
"icedtea_spice_garlic",
"icedtea_spice_salt",
"icedtea_spice_sugar",
"jellybean",
"jellybean_spice_chili",
"jellybean_spice_garlic",
"jellybean_spice_salt",
"jellybean_spice_sugar",
"jellyopop",
"jellyopop_spice_chili",
"jellyopop_spice_garlic",
"jellyopop_spice_salt",
"jellyopop_spice_sugar",
"leafymeatsouffle",
"leafymeatsouffle_spice_chili",
"leafymeatsouffle_spice_garlic",
"leafymeatsouffle_spice_salt",
"leafymeatsouffle_spice_sugar",
"kabobs",
"kabobs_spice_chili",
"kabobs_spice_garlic",
"kabobs_spice_salt",
"kabobs_spice_sugar",
"mandrakesoup",
"mandrakesoup_spice_chili",
"mandrakesoup_spice_garlic",
"mandrakesoup_spice_salt",
"mandrakesoup_spice_sugar",
"meatballs",
"meatballs_spice_chili",
"meatballs_spice_garlic",
"meatballs_spice_salt",
"meatballs_spice_sugar",
"bonestew",
"bonestew_spice_chili",
"bonestew_spice_garlic",
"bonestew_spice_salt",
"bonestew_spice_sugar",
"watermelonicle",
"watermelonicle_spice_chili",
"watermelonicle_spice_garlic",
"watermelonicle_spice_salt",
"watermelonicle_spice_sugar",
"batnosehat",
"batnosehat_spice_chili",
"batnosehat_spice_garlic",
"batnosehat_spice_salt",
"batnosehat_spice_sugar",
"monsterlasagna",
"monsterlasagna_spice_chili",
"monsterlasagna_spice_garlic",
"monsterlasagna_spice_salt",
"monsterlasagna_spice_sugar",
"shroomcake",
"shroomcake_spice_chili",
"shroomcake_spice_garlic",
"shroomcake_spice_salt",
"shroomcake_spice_sugar",
"musselbouillabaise",
"musselbouillabaise_spice_chili",
"musselbouillabaise_spice_garlic",
"musselbouillabaise_spice_salt",
"musselbouillabaise_spice_sugar",
"leafloaf",
"leafloaf_spice_chili",
"leafloaf_spice_garlic",
"leafloaf_spice_salt",
"leafloaf_spice_sugar",
"nettlelosange",
"nettlelosange_spice_chili",
"nettlelosange_spice_garlic",
"nettlelosange_spice_salt",
"nettlelosange_spice_sugar",
"perogies",
"perogies_spice_chili",
"perogies_spice_garlic",
"perogies_spice_salt",
"perogies_spice_sugar",
"justeggs",
"justeggs_spice_chili",
"justeggs_spice_garlic",
"justeggs_spice_salt",
"justeggs_spice_sugar",
"powcake",
"powcake_spice_chili",
"powcake_spice_garlic",
"powcake_spice_salt",
"powcake_spice_sugar",
"pumpkincookie",
"pumpkincookie_spice_chili",
"pumpkincookie_spice_garlic",
"pumpkincookie_spice_salt",
"pumpkincookie_spice_sugar",
"ratatouille",
"ratatouille_spice_chili",
"ratatouille_spice_garlic",
"ratatouille_spice_salt",
"ratatouille_spice_sugar",
"salsa",
"salsa_spice_chili",
"salsa_spice_garlic",
"salsa_spice_salt",
"salsa_spice_sugar",
"seafoodgumbo",
"seafoodgumbo_spice_chili",
"seafoodgumbo_spice_garlic",
"seafoodgumbo_spice_salt",
"seafoodgumbo_spice_sugar",
"sharkfinsoup",
"sharkfinsoup_spice_chili",
"sharkfinsoup_spice_garlic",
"sharkfinsoup_spice_salt",
"sharkfinsoup_spice_sugar",
"snakebonesoup",
"snakebonesoup_spice_chili",
"snakebonesoup_spice_garlic",
"snakebonesoup_spice_salt",
"snakebonesoup_spice_sugar",
"sweettea",
"sweettea_spice_chili",
"sweettea_spice_garlic",
"sweettea_spice_salt",
"sweettea_spice_sugar",
"hotchili",
"hotchili_spice_chili",
"hotchili_spice_garlic",
"hotchili_spice_salt",
"hotchili_spice_sugar",
"spicyvegstinger",
"spicyvegstinger_spice_chili",
"spicyvegstinger_spice_garlic",
"spicyvegstinger_spice_salt",
"spicyvegstinger_spice_sugar",
"vegstinger",
"vegstinger_spice_chili",
"vegstinger_spice_garlic",
"vegstinger_spice_salt",
"vegstinger_spice_sugar",
"steamedhamsandwich",
"steamedhamsandwich_spice_chili",
"steamedhamsandwich_spice_garlic",
"steamedhamsandwich_spice_salt",
"steamedhamsandwich_spice_sugar",
"stuffedeggplant",
"stuffedeggplant_spice_chili",
"stuffedeggplant_spice_garlic",
"stuffedeggplant_spice_salt",
"stuffedeggplant_spice_sugar",
"barnaclestuffedfishhead",
"barnaclestuffedfishhead_spice_chili",
"barnaclestuffedfishhead_spice_garlic",
"barnaclestuffedfishhead_spice_salt",
"barnaclestuffedfishhead_spice_sugar",
"pepperpopper",
"pepperpopper_spice_chili",
"pepperpopper_spice_garlic",
"pepperpopper_spice_salt",
"pepperpopper_spice_sugar",
"surfnturf",
"surfnturf_spice_chili",
"surfnturf_spice_garlic",
"surfnturf_spice_salt",
"surfnturf_spice_sugar",
"taffy",
"taffy_spice_chili",
"taffy_spice_garlic",
"taffy_spice_salt",
"taffy_spice_sugar",
"talleggs",
"talleggs_spice_chili",
"talleggs_spice_garlic",
"talleggs_spice_salt",
"talleggs_spice_sugar",
"tea",
"tea_spice_chili",
"tea_spice_garlic",
"tea_spice_salt",
"tea_spice_sugar",
"trailmix",
"trailmix_spice_chili",
"trailmix_spice_garlic",
"trailmix_spice_salt",
"trailmix_spice_sugar",
"tropicalbouillabaisse",
"tropicalbouillabaisse_spice_chili",
"tropicalbouillabaisse_spice_garlic",
"tropicalbouillabaisse_spice_salt",
"tropicalbouillabaisse_spice_sugar",
"turkeydinner",
"turkeydinner_spice_chili",
"turkeydinner_spice_garlic",
"turkeydinner_spice_salt",
"turkeydinner_spice_sugar",
"unagi",
"unagi_spice_chili",
"unagi_spice_garlic",
"unagi_spice_salt",
"unagi_spice_sugar",
"leafymeatburger",
"leafymeatburger_spice_chili",
"leafymeatburger_spice_garlic",
"leafymeatburger_spice_salt",
"leafymeatburger_spice_sugar",
"waffles",
"waffles_spice_chili",
"waffles_spice_garlic",
"waffles_spice_salt",
"waffles_spice_sugar",
"wetgoop",
"wetgoop_spice_chili",
"wetgoop_spice_garlic",
"wetgoop_spice_salt",
"wetgoop_spice_sugar",
"lobsterbisque",
"lobsterbisque_spice_chili",
"lobsterbisque_spice_garlic",
"lobsterbisque_spice_salt",
"lobsterbisque_spice_sugar",
"lobsterdinner",
"lobsterdinner_spice_chili",
"lobsterdinner_spice_garlic",
"lobsterdinner_spice_salt",
"lobsterdinner_spice_sugar",
"gazpacho",
"gazpacho_spice_chili",
"gazpacho_spice_garlic",
"gazpacho_spice_salt",
"gazpacho_spice_sugar",
"bonesoup",
"bonesoup_spice_chili",
"bonesoup_spice_garlic",
"bonesoup_spice_salt",
"bonesoup_spice_sugar",
"frogfishbowl",
"frogfishbowl_spice_chili",
"frogfishbowl_spice_garlic",
"frogfishbowl_spice_salt",
"frogfishbowl_spice_sugar",
"freshfruitcrepes",
"freshfruitcrepes_spice_chili",
"freshfruitcrepes_spice_garlic",
"freshfruitcrepes_spice_salt",
"freshfruitcrepes_spice_sugar",
"glowberrymousse",
"glowberrymousse_spice_chili",
"glowberrymousse_spice_garlic",
"glowberrymousse_spice_salt",
"glowberrymousse_spice_sugar",
"nightmarepie",
"nightmarepie_spice_chili",
"nightmarepie_spice_garlic",
"nightmarepie_spice_salt",
"nightmarepie_spice_sugar",
"dragonchilisalad",
"dragonchilisalad_spice_chili",
"dragonchilisalad_spice_garlic",
"dragonchilisalad_spice_salt",
"dragonchilisalad_spice_sugar",
"monstertartare",
"monstertartare_spice_chili",
"monstertartare_spice_garlic",
"monstertartare_spice_salt",
"monstertartare_spice_sugar",
"moqueca",
"moqueca_spice_chili",
"moqueca_spice_garlic",
"moqueca_spice_salt",
"moqueca_spice_sugar",  
"potatosouffle",
"potatosouffle_spice_chili",
"potatosouffle_spice_garlic",
"potatosouffle_spice_salt",
"potatosouffle_spice_sugar",
"voltgoatjelly",
"voltgoatjelly_spice_chili",
"voltgoatjelly_spice_garlic",
"voltgoatjelly_spice_salt",
"voltgoatjelly_spice_sugar",
"meat_dried",
"monstermeat_dried",
"smallmeat_dried",
"hambat",
"seeds",
"seeds_cooked",
"humanmeat_dried",
"kelp_dried",
"acorn_cooked",
"asparagus_cooked",
"barnacle_cooked",
"batnose_cooked",
"batwing_cooked",
"berries_cooked",
"berries_juicy_cooked",
"bird_egg_cooked",
"blue_cap_cooked",
"cactus_meat_cooked",
"carrot_cooked",
"cave_banana_cooked",
"cooked_mandrake",
"cookedmeat",
"cookedmeatsmall",
"corn_cooked",
"dragonfruit_cooked",
"drumstick_cooked",
"durian_cooked",
"eel_cooked",
"eggplant_cooked",
"fig_cooked",
"fish_cooked",
"fishmeat_cooked",
"fishmeat_small_cooked",
"froglegs_cooked",
"garlic_cooked",
"green_cap_cooked",
"humanmeat_cooked",
"kelp_cooked",
"moon_cap_cooked",
"onion_cooked",
"pepper_cooked",
"plantmeat_cooked",
"pomegranate_cooked",
"potato_cooked",
"pumpkin_cooked",
"red_cap_cooked",
"rock_avocado_fruit_ripe_cooked",
"tallbirdegg_cooked",
"tomato_cooked",
"trunk_cooked",
"watermelon_cooked",
"wobster_sheller_dead_cooked"}

local function SaltBoxPlus(inst)
        inst:AddTag("saltbox_valid")
end

for i, prefab in ipairs(PREFABS_FOR_POSTINIT) do
    AddPrefabPostInit(prefab, SaltBoxPlus)
end